### ISSUE TITLE
Unable to use pandass rolling in a strategy

### ISSUE THREAD

**Issue by riodda** [kernc/backtesting.py#225]
### Expected Behavior

performs a rolling calculation using pandas function, with aim of backtest optimize windows size and barriers.

### Actual Behavior
```
Traceback (most recent call last):

  File "/home/dario/Documenti/Python/Trading/Random_Forest_trader/normalizer_K_binance_backtest.py", line 126, in <module>
    backtest = bt.run()

  File "/home/dario/.local/lib/python3.8/site-packages/backtesting/backtesting.py", line 1130, in run
    strategy.init()

  File "/home/dario/Documenti/Python/Trading/Random_Forest_trader/normalizer_K_binance_backtest.py", line 74, in init
    self.normalized_low=self.I(lri_signal,self.data,self.lookback,self.low_barrier,self.high_barrier)

  File "/home/dario/.local/lib/python3.8/site-packages/backtesting/backtesting.py", line 127, in I
    raise RuntimeError(f'Indicator "{name}" errored with exception: {e}')

RuntimeError: Indicator "lri_signal(100,0,100)" errored with exception: '_Array' object has no attribute 'rolling'

```

### Steps to Reproduce

I wrote this function:

```
def lri_signal(_data,_lookback,_low_barrier,_high_barrier):
    
    _data['lri_low']=(_data['Low']-_data['Low'].rolling(center=False,window=_lookback,min_periods=1).min())/(_data['Low'].rolling(center=False,window=_lookback,min_periods=1).max()-_data['Low'].rolling(center=False,window=_lookback,min_periods=1).min())*100
    _data['lri_high']=(_data['High']-_data['High'].rolling(center=False,window=_lookback,min_periods=1).min())/(_data['High'].rolling(center=False,window=_lookback,min_periods=1).max()-_data['High'].rolling(center=False,window=_lookback,min_periods=1).min())*100
    
    _filter_buy=(_data['lri_low']<=_low_barrier) & (_data['lri_low'].shift(1)>_low_barrier) & (_data['lri_low'].shift(2)>_low_barrier)
    _filter_sell = (_data['lri_high']>=_high_barrier) & (_data['lri_high'].shift(-1)<_high_barrier) & (_data['lri_high'].shift(-2)<_high_barrier)
    _data.loc[_filter_buy, 'signal' ]=1
    _data.loc[_filter_sell, 'signal' ]=-1

```
And i was trying to use the function in this stragegy:

```
class Normalized_Indicator(TrailingStrategy):
    lookback = 100
    low_barrier = 0
    high_barrier = 100
    zero = 0
    stop_loss = 90
    take_profit = 110
    short_positions = False
    
    def init(self):
        self.normalized_low=self.I(lri_signal,self.data,self.lookback,self.low_barrier,self.high_barrier)
        super().init()
        
    def next(self):
        price = self.data.Close[-1]
        if crossover(self.data.signal, self.zero):
            if (not self.position):
                self.buy(sl=self.stop_loss*price/100, tp = self.take_profit*price/100)
        
        if (self.position and crossover(self.zero,self.data.signal)):
            self.position.close()
        
        if crossover(self.zero, self.data.signal) :
            if (not self.position) and (self.short_positions == True):
                self.sell()
        
        if (self.position and crossover(self.zero,self.data.signal)):
            self.position.close()
        
        self.set_trailing_sl(self.trailing_atr)
```

But i receive a runtime error, is this related to the impossibility of backtesting of using dataframes ? Or i did some programming mistake i can't find?

**Comment by kernc** [comment]
Using [`.df` accessor](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data) should work for you:
```py
self.normalized_low = self.I(lri_signal, self.data.df, self.lookback, self.low_barrier, self.high_barrier)
```
And add some spaces, goddamnit!

**Comment by riodda** [comment]
Thanks for your help...will work on my spaces !
