### ISSUE TITLE
NaNError while there aren't any NaN values in my dataframe

### ISSUE THREAD

**Issue by JanssensKobe** [kernc/backtesting.py#268]
Okay, so I'm trying to backtest a strategy on this dataframe:
```
                       Open    High     Low   Close       Volume
Date
2020-10-13 20:16:00   51.06   51.06   51.06   51.06       0.0000
2020-10-13 20:17:00   51.06   51.06   51.06   51.06       0.0000
2020-10-13 20:18:00   51.06   51.06   51.06   51.06       0.0000
2020-10-13 20:19:00   51.06   51.06   51.06   51.06       0.0000
2020-10-13 20:20:00   51.06   51.06   51.06   51.06       0.0000
...                     ...     ...     ...     ...          ...
2021-03-01 17:31:00  373.01  374.04  372.99  373.92  102053.7824
2021-03-01 17:32:00  373.92  373.92  371.53  371.81   11862.2328
2021-03-01 17:33:00  371.81  373.52  371.81  373.52   19149.9888
2021-03-01 17:34:00  373.52  373.96  372.53  372.77   36027.0162
2021-03-01 17:35:00  372.77  372.77  371.63  371.63     807.3434
```

But when I try to run it I get an ValueError:
```
Traceback (most recent call last):
  File "D:\backtesting.py\ShiftMA.py", line 51, in <module>
    bt = Backtest(ohlcv, ShiftMA, cash=10000, commission=0)
  File "C:\Users\kobej\AppData\Local\Programs\Python\Python39\lib\site-packages\backtesting\backtesting.py", line 1065, in __init__
    raise ValueError('Some OHLC values are missing (NaN). '
ValueError: Some OHLC values are missing (NaN). Please strip those lines with `df.dropna()` or fill them in with `df.interpolate()` or whatever.
```

I've quickly checked my data and used this piece of code to check if there are any NaN values `ohlcv.isnull().sum().sum()` but there aren't any.

**Comment by kernc** [comment]
So `ohlcv.isnull().any()` returns False? :thinking:  That's quite weird given that's near-exactly the code that gets executed:
https://github.com/kernc/backtesting.py/blob/73e1534428fc2db9e681030862133b5067508520/backtesting/backtesting.py#L1064-L1067

**Comment by JanssensKobe** [comment]
Indeed, this is the output:
```
Open      False
High      False
Low       False
Close     False
Volume    False
dtype: bool
```

**Comment by JanssensKobe** [comment]
Okay, my fault. I was resampling my dataframe later in my script and that lead to NaN values.
