### ISSUE TITLE
Optimize ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by mavverick** [kernc/backtesting.py#46]
### Expected Behavior
Optimize strategy

### Actual Behavior
When I try optimize strategy with 3 variables (two emas and 1 dmi) it begin and after a few seconds  return this  error

```py
print(bt.optimize(dmi=range(3,17,1),n1=range(3,17,1),n2=range(18,40,1),maximize='Equity 

Final [$]'))
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 831, in optimize
    for _, stats in self._mp_task([params]):
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 850, in _mp_task
    for params in param_combos)
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 849, in <listcomp>
    return [(params, stats) for params, stats in ((params, self.run(**params))
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 850, in <genexpr>
    for params in param_combos)
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 713, in run
    self._results = self._compute_stats(broker, strategy)
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 885, in _compute_stats
    dd_dur, dd_peaks = _drawdown_duration_peaks(dd, data.index)
  File "C:\Users\maxi\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 870, in _drawdown_duration_peaks
    peaks[j] = dd[i:j].max()
  File "C:\Users\maxi\Anaconda3\lib\site-packages\numpy\core\_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

### Steps to Reproduce

1.`print(bt.optimize(dmi=range(3,17,1),n1=range(3,17,1),n2=range(18,40,1),maximize='Equity Final [$]'))`
2.
3.

### Additional info
I can do `bt.optimize(n1=range(3,17,1),n2=range(18,40,1),maximize='Equity Final [$]'))`
or `bt.optimize(dmi=range(3,17,1),maximize='Equity Final [$]'))`

- Backtesting version:
0.1.4

**Comment by kernc** [comment]
A regression introduced in https://github.com/kernc/backtesting.py/commit/d08524904d5ace93ed63cc5356f659ad86fdeda4.
Thanks!

**Comment by hotsun** [comment]
> A regression introduced in [d085249](https://github.com/kernc/backtesting.py/commit/d08524904d5ace93ed63cc5356f659ad86fdeda4).
> Thanks!

If the test has drawdown all the time and max drawdown period is the same as the data range it will still have the same error:
"""
Traceback (most recent call last):
  File "/Users/sunny/miniconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/backtesting/backtesting.py", line 850, in _mp_task
    for params in param_combos)
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/backtesting/backtesting.py", line 849, in <listcomp>
    return [(params, stats) for params, stats in ((params, self.run(**params))
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/backtesting/backtesting.py", line 850, in <genexpr>
    for params in param_combos)
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/backtesting/backtesting.py", line 713, in run
    self._results = self._compute_stats(broker, strategy)
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/backtesting/backtesting.py", line 885, in _compute_stats
    dd_dur, dd_peaks = _drawdown_duration_peaks(dd, data.index)
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/backtesting/backtesting.py", line 870, in _drawdown_duration_peaks
    peaks[j] = dd[i:j].max()
  File "/Users/sunny/miniconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 28, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation maximum which has no identity
"""

**Comment by hotsun** [comment]
I saw the latest commit has fixed this, please ignore my comment.
https://github.com/kernc/backtesting.py/commit/73f893145edb11759dd30491489b2708ce6da8d2
