### ISSUE TITLE
AttributeError: unexpected attribute 'callback' to Range1d, similar attributes are js_event_callbacks

### ISSUE THREAD

**Issue by khaizon** [kernc/backtesting.py#48]
Unable to run `bt.plot()` using sample code. I'm a beginner with  python and would really appreciate some help with this issue.

Ran this on both main anaconda environment (python 3.7.6) and a virtual anaconda environment (python 3.8.1) 
### Actual Behavior
This was the error produce when I ran the sample code on VSC.
Traceback (most recent call last):
  File "c:/Users/tohka/Desktop/Python Stuff/backtest.py", line 23, in <module>
    bt.plot()
  File "C:\Users\tohka\Anaconda3\envs\py38\lib\site-packages\backtesting\backtesting.py", line 1000, in plot
    plot(
  File "C:\Users\tohka\Anaconda3\envs\py38\lib\site-packages\backtesting\_plotting.py", line 545, in plot
    fig_ohlc.x_range.callback = CustomJS(args=custom_js_args,
  File "C:\Users\tohka\Anaconda3\envs\py38\lib\site-packages\bokeh\core\has_props.py", line 280, in __setattr__
    raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
AttributeError: unexpected attribute 'callback' to Range1d, similar attributes are js_event_callbacks

### Additional info

- Backtesting version:
0.1.5

**Comment by Realmlai** [comment]
me too
I got "AttributeError: unexpected attribute 'callback' to Range1d, similar attributes are js_event_callbacks"
after bt.plot()

**Comment by kernc** [comment]
This is a regression with Bokeh 2.0.0 released today. A prompt workaround is to downgrade:
```bash
pip install bokeh==0.1.4
```

**Comment by kernc** [comment]
Backtesting v0.1.6 released, `pip install -U backtesting`.

**Comment by Realmlai** [comment]
Thank you kernc
