### ISSUE TITLE
backtest.optimize throws error

### ISSUE THREAD

**Issue by Kayne88** [kernc/backtesting.py#500]
### Expected Behavior

`backtest.optimize(fast_period=range(2,10,2),medium_period=range(6,20,2),slow_period=range(10,30,2))`
is executing without error.

### Actual Behavior

It returns this traceback:

> Traceback (most recent call last):
  File "c:/Users/User/Documents/Trading/Back testing/run_backtest.py", line 19, in <module>
    optimal_parameters = backtest.optimize(fast_period=range(2,10,2),medium_period=range(6,20,2),slow_period=range(10,30,2))
  File "C:\Users\User\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 1487, in optimize
    output = _optimize_grid()
  File "C:\Users\User\Anaconda3\lib\site-packages\backtesting\backtesting.py", line 1324, in _optimize_grid
    rand = np.random.RandomState(random_state).random
AttributeError: 'mtrand.RandomState' object has no attribute 'random'

### Analysis

If I look at numpy RandomState doc: https://numpy.org/doc/1.16/reference/generated/numpy.random.RandomState.html
There is indeed no method handle called random, only rand.

### Additional info

![bug backtesting](https://user-images.githubusercontent.com/92090894/136549728-e079b628-48e3-408f-8e6d-749e5241228c.PNG)

- Backtesting version: 0.3.2

**Comment by kernc** [comment]
Apparently this only happens on some platforms. For me:
```py
>>> np.__version__
'1.21.2'
>>> np.random.RandomState().random()
0.9464831509552952
```
But the method is not documented. Therefore, thanks!
