### ISSUE TITLE
ValueError: `data` must be a pandas.DataFrame with columns 'Open', 'High', 'Low', 'Close', and (optionally) 'Volume'

### ISSUE THREAD

**Issue by windowshopr** [kernc/backtesting.py#632]
### Expected Behavior
Running into this error and I can't figure out why as I AM feeding it a `dataframe` that is (I'm assuming almost) identical to the sample `GOOG` dataset provided, but backtesting doesn't like it for some reason?

### Actual Behavior

```
Traceback (most recent call last):
  File "testKernc.py", line 93, in <module>
    bt = Backtest(df, StrategyClass, commission=.001, exclusive_orders=True)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\lib\site-packages\backtesting\backtesting.py", line 1067, in __init__
    raise ValueError("`data` must be a pandas.DataFrame with columns "
ValueError: `data` must be a pandas.DataFrame with columns 'Open', 'High', 'Low', 'Close', and (optionally) 'Volume'
```

### Steps to Reproduce

To reproduce, download the 5 minute SPY dataset that I'm using from my [google drive here](https://drive.google.com/file/d/10Jzzj-2K-4rtvgHQeJai4YWNL0rB1cau/view?usp=sharing), place it in the same folder as the below script and run it.

```python

from pandas import read_csv, to_datetime
import talib
from numpy import where
# from utils.Broker import BrokerClass
from backtesting import Backtest, Strategy
from backtesting.test import GOOG


# ---------------------------------------------------------------------------- #
#                            Import/Prepare Dataset                            #
# ---------------------------------------------------------------------------- #
# Read in global df
datapath = "./SPY5min.csv"
df = read_csv(datapath)
df['time'] = to_datetime(df['time'])
# Rename the columns to uppercase
df = df.rename(columns={"time": "Datetime",
                        "open":" Open",
                        "high": "High",
                        "low": "Low",
                        "close": "Close",
                        "volume": "Volume"})
# Set the datetime index
df = df.set_index("Datetime")
# ------------------------ End Import/Prepare Dataset ------------------------ #


# ---------------------------------------------------------------------------- #
#                                Strategy Class                                #
# ---------------------------------------------------------------------------- #
# Define the stratey class with init and next functions
class StrategyClass(Strategy):

    def init(self):

        open = self.data.Open
        high = self.data.High
        low = self.data.Low
        close = self.data.Close
        volume = self.data.Volume

        self.out = talib.SMA(close, timeperiod=5)
        self.out2 = talib.EMA(close, timeperiod=20)

        # Order conditions
        self.enter_long = where((high > self.out) &
                                (self.out > self.out2),
                                True, False)
        self.enter_short = where((low < self.out) &
                                (self.out < self.out2),
                                True, False)
        self.exit_long = self.enter_short
        self.exit_short = self.enter_long

    def next(self):
        if self.enter_long:
            if self.position.size > 0:
                return
            if self.position.size < 0:
                self.close(portion=1.0)
            self.buy(size=1.0, limit=self.data.Close+0.10, stop=None, sl=None, tp=None)

        elif self.exit_long and self.position.size > 0:
            self.close()

        elif self.enter_short:
            if self.position.size < 0:
                return
            if self.position.size > 0:
                self.close(portion=1.0)
            self.sell(size=1.0, limit=self.data.Close-0.10, stop=None, sl=None, tp=None)

        elif self.exit_short and self.position.size < 0:
            self.close()
# ---------------------------- End Strategy Class ---------------------------- #


# ---------------------------------------------------------------------------- #
#                              Main Program Start                              #
# ---------------------------------------------------------------------------- #
# Inspect this df with the default GOOG one provided by backtesting
print(df)
print(type(df))
print(GOOG)
print(type(GOOG))

bt = Backtest(df, StrategyClass, commission=.001, exclusive_orders=True)
stats = bt.run()
# -------------------------- End Main Program Start -------------------------- #

```

### Additional info

From the screenshot below, you'll see the dataset I'm trying to use on top, and the GOOG dataset on the bottom. Only difference is the index, which I've made as the Datetime column in mine:

![image](https://user-images.githubusercontent.com/40477419/163687234-8e532223-34fe-4424-b879-833e9064646b.png)

Both are showing as `dataframe` objects with the correct column names, so I'm wondering if it's because I'm trying to use an intraday dataset and it doesn't like the index? I've also tried it where the `Datetime` column is just a regular column and not the index column, but same issue. What am I missing?

I did a search in the issues for ``data` must be a pandas.DataFrame` and a few others but didn't see anything on it so figured I'd post. Thanks!

- Backtesting version: 0.3.3   
- Windows 10
- Python 3.7.9

**Comment by windowshopr** [comment]
I noticed that it has to do with this part of the code in backtesting (starting line 1066):

```
        if len(data.columns.intersection({'Open', 'High', 'Low', 'Close', 'Volume'})) != 5:
            raise ValueError("`data` must be a pandas.DataFrame with columns "
                             "'Open', 'High', 'Low', 'Close', and (optionally) 'Volume'")
```

so in my main script I added:

```
print(len(df.columns.intersection({'Open', 'High', 'Low', 'Close', 'Volume'})))
```

and it's only printing out 4, when it should print out 5, yet all the column names are there?

**Comment by windowshopr** [comment]
I figured it out!

For some reason, it didn't "see" "Open" as a column upon reading in the CSV file. No idea why that would be, but I fixed it by adding:

`df = df.reindex(columns=['Open', 'High', 'Low', 'Close', 'Volume'])`

as the last line in the import dataset section. This forced all column names to be "seen". Frustrating but this did it. Thanks for letting me work that out!
