### ISSUE TITLE
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'. Using resample_apply()

### ISSUE THREAD

**Issue by SlavaBurmistrov** [kernc/backtesting.py#825]
### Expected Behavior
I am trying to resample the 5m OHLCV to 1h OHLCV using the code below. 
```python

        self.rsi_5m = self.I(ta.rsi, pd.Series(self.data.Close), self.rsi_window)
        self.rsi_1h = resample_apply("4H", ta.rsi, pd.Series(self.data.Close), self.rsi_window)
```
I have verified that my index is set to DatetimeIndex and all of the indexes are dates.

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

### Actual Behavior

Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\backtesting\main.py", line 34, in <module>
    stats = bt.optimize(
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\backtesting\backtesting.py", line 1277, in optimize
    stats = self._results if self._results is not None else self.run()
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\backtesting\backtesting.py", line 1139, in run
    strategy.init()
  File "C:\Users\admin\PycharmProjects\backtesting\main.py", line 19, in init
    self.rsi_1h = resample_apply("4H", ta.rsi, pd.Series(self.data.Close), self.rsi_window)
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\backtesting\lib.py", line 294, in resample_apply
    resampled = series.resample(rule, label='right').agg(agg).dropna()
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\pandas\core\series.py", line 5872, in resample
    return super().resample(
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\pandas\core\generic.py", line 8858, in resample
    return get_resampler(
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\pandas\core\resample.py", line 1544, in get_resampler
    return tg._get_resampler(obj, kind=kind)
  File "C:\Users\admin\PycharmProjects\backtesting\venv\lib\site-packages\pandas\core\resample.py", line 1725, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

### Additional info 
Time                              Open     High      Low    Close    Volume                                                     
2022-07-18 12:15:00  22059.0  22068.9  21936.7  21971.6  4718.322
2022-07-18 12:20:00  21971.6  21997.5  21900.7  21915.6  4562.186
2022-07-18 12:25:00  21915.5  21987.0  21913.0  21982.3  2600.936
2022-07-18 12:30:00  21982.6  22110.7  21943.0  22062.1  5301.631
2022-07-18 12:35:00  22062.4  22133.0  22029.5  22107.0  2870.428
...                      ...      ...      ...      ...       ...
2022-11-02 14:55:00  20428.1  20436.3  20422.2  20424.3   478.272
2022-11-02 15:00:00  20424.3  20426.3  20407.4  20407.4   558.910
2022-11-02 15:05:00  20407.5  20415.5  20407.1  20414.3   605.311
2022-11-02 15:10:00  20414.3  20414.4  20392.7  20399.7   642.506
2022-11-02 15:15:00  20399.7  20401.6  20397.5  20398.0   145.078

This how the dataset looks

**Comment by kernc** [comment]
With:
```py
resample_apply("4H", ta.rsi, pd.Series(self.data.Close), self.rsi_window)
```
you are casting [`Strategy.data.Close` _ndarray_](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data) to Series without an index! Use `self.data.Close.s`, or re-attach a datetime index manually.

**Comment by SlavaBurmistrov** [comment]
> With:
> 
> ```python
> resample_apply("4H", ta.rsi, pd.Series(self.data.Close), self.rsi_window)
> ```
> 
> you are casting [`Strategy.data.Close` _ndarray_](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data) to Series without an index! Use `self.data.Close.s`, or re-attach a datetime index manually.
Thank you!
