### ISSUE TITLE
bt.blot() results in random AssertionError

### ISSUE THREAD

**Issue by trueToastedCode** [kernc/backtesting.py#911]
### Expected Behavior
`bt.plot()`
> plot

### Actual Behavior
```
Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
```

### Steps to Reproduce
Execute `bt.plot()` multiple times. Usually works the first time, after that it may occur at any time. Only a Kernel Restart makes it functional again - otherwise `bt.plot()` will then always end with the error.

- Python 3.10
- Backtesting 0.3.3
- Bokeh 2.4.3
- OS: MacOS Ventura 13.2 (ARM64)

**Comment by trueToastedCode** [comment]
Ended up commenting that line in iostream.py, seems to work
```
nano +182 "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/iostream.py"
>>> assert 0 < size <= self._size
>>> # assert 0 < size <= self._size
```

**Comment by kernc** [comment]
>     Traceback (most recent call last):
>       File "/Users/lennard/miniconda3/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
>         ...
>       File "/Users/lennard/miniconda3/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
>         assert 0 < size <= self._size
>     AssertionError

Sorry, but none of the mentioned files indicate this is our issue, and we use neither zmq nor tornado. Seems like this has something to do with your Jupyter Notebook installation/runtime or, at most relevant, Bokeh notebook output.

**Comment by trueToastedCode** [comment]
Update: It seems to work after installing the environment with Python 3.8 instead of 3.10.
