### ISSUE TITLE
'_Array' object has no attribute 'pct_change'

### ISSUE THREAD

**Issue by andreasklippinge** [kernc/backtesting.py#936]
### Expected Behavior
Hey, 

Im trying to capitalize on price movements that are outliers. 
My code below: 

```
import yfinance as yf
import numpy as np
from backtesting import Backtest, Strategy
import backtesting
backtesting.set_bokeh_output(notebook=False)

def opportunity(df):
    df["pct_change"] = abs(df['Close'].pct_change())
    df["std_dev_change"] = df["pct_change"].expanding().std() * 2
    df = df.fillna(0)
    pct_change_np = df["pct_change"].to_numpy()
    std_dev_change_np = df["std_dev_change"].to_numpy()
    diff = std_dev_change_np - pct_change_np
    return diff
     
class Divergence_Strategy_Long(Strategy):
    def init(self):
        self.signal = self.I(opportunity, self.data, plot=True, name="Outlier", color="blue")
    def next(self):
        if self.signal > 0:
            self.buy(size=0.75)
        elif self.position:
            self.position.close()

ticker = "^OMX"
df = yf.download(ticker, period="max", interval = "1d", progress=False, rounding=False, ignore_tz=(True))
bt = Backtest(df, Divergence_Strategy_Long, exclusive_orders=False, cash=1_000_000, trade_on_close=(False),)
stats = bt.run()
print(stats)
```
So what I'm trying to acheive and backtest is when the self.signal value is higher than 0, the price change in percent is higher than the standard deviation times 2. The standard deviation is calculated on the percentage change of the closing price. 

### Actual Behavior
```
Traceback (most recent call last):

  File "C:\Users\Andreas\anaconda3\lib\site-packages\backtesting\backtesting.py", line 127, in I
    value = func(*args, **kwargs)

  File "C:\Users\Andreas\Aktieanalys\untitled3.py", line 8, in opportunity
    df["pct_change"] = abs(df['Close'].pct_change())

AttributeError: '_Array' object has no attribute 'pct_change'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Andreas\Aktieanalys\untitled3.py", line 28, in <module>
    stats = bt.run()

  File "C:\Users\Andreas\anaconda3\lib\site-packages\backtesting\backtesting.py", line 1139, in run
    strategy.init()

  File "C:\Users\Andreas\Aktieanalys\untitled3.py", line 18, in init
    self.signal = self.I(opportunity, self.data, plot=True, name="Outlier", color="blue")

  File "C:\Users\Andreas\anaconda3\lib\site-packages\backtesting\backtesting.py", line 129, in I
    raise RuntimeError(f'Indicator "{name}" errored with exception: {e}')

RuntimeError: Indicator "Outlier" errored with exception: '_Array' object has no attribute 'pct_change'
```

I've tried solving it with ChatGPT but it just sends me in a loop with solutions that do not work. As far as I can understand, the problem stems from row 9, that numpy does not support the ".expanding". 
I do not know how to resolve/change the code to make it fit into the self.I() argument, and would be thankful for any feedback. 

Thanks a lot in advance.

**Comment by kernc** [comment]
If you opportunity indicator expects a df, you are simply missing a [`.df` accessor](https://kernc.github.io/backtesting.py/doc/backtesting/backtesting.html#backtesting.backtesting.Strategy.data):
```py
self.signal = self.I(opportunity, self.data.df)
```
